name: Build ProxyClient On Windows
on:
  push:
    branches:
      - actions-build
jobs:
  build:
    name: VTurbo on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.ACTIONS_BUILD }}
          native-image-job-reports: 'true'

      - name: Build
        run: .\gradlew.bat :proxy-client:nativeBuild
        shell: pwsh

      - name: copy
        run: New-Item -Name "staging" -ItemType "directory"; Copy-Item ".\proxy-client\build\native\nativeCompile\ProxyClient.exe" -Destination "staging"
        shell: pwsh

      - name: get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: ProxyClient-${{ steps.current-time.outputs.formattedTime }}-${{ matrix.os }}
          path: staging